--==EVENTS==
--https://www.youtube.com/watch?v=-acYafWcdoc&list=PL9XabkF_A5YjFHJpJV5f5ta6cx81Ku_4k&index=7

term.clear()
term.setCursorPos(1,1)

print("Press any key or mouse (mouse=AdvComputer only!)")

event, param1 = os.pullEvent() -- pull event returns 2 variables!

print("Event: "..event.." Param1: "..param1.." <-- every key has a different number")

-- Different events will generate a different number of events. 
-- (up to 5, mostly 4)

print("Terminate loop with: q")
count = 0
while param1 ~= "q" do
    event, param1, param2, param3, param4 = os.pullEvent()
    print(count.." Event: "..tostring(event).." p1: "..tostring(param1).." p2: "..tostring(param2).." p3: "..tostring(param3).." p4: "..tostring(param4))
    count = count + 1
end

-- Peripherals can generate events for a computer!

--EXAMPLE [chat events and chatbox]
-- Add a chatbox to bottom of your computer for next example.
print("Write something in chat!")
chatBox = peripheral.wrap("bottom")
event, p1, p2 = os.pullEvent("chat")
print(" cBox: "..tostring(chatBox))
if chatBox then
    chatBox.say("Hi, your Events program used the chatbox to respond here!")
end
print("Received chat event: "..tostring(event).." p1: "..tostring(p1).." p2: "..tostring(p2))

